# Generated by Django 2.2.2 on 2019-06-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfolder',
            name='id',
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='folderId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
