# Generated by Django 2.2.2 on 2019-06-17 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docviewer', '0002_auto_20190617_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfolder',
            name='folderPath',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
